image: alpine:latest

pages:
  tags:
    - Docker
  script:
    - mkdir public
    - cp emacs-magit.html public/index.html
    - cp rethink.css public/
  artifacts:
    paths:
      - public
  only:
    - master
